### ISSUE TITLE
ClusterStatus conflicts with "ClusterStatus" enum

### ISSUE THREAD

**Issue by Sijoma** [camunda-community-hub/console-customer-api-go#1]
After generation the files were edited manually as the status field on the Cluster will create things that conflict with the "ClusterStatus". Thus I modified the Swagger file so that it is named status2. Then everything will create properly but you have to manually edit the files again on some things.

Not sure how to fix this best.

**Comment by multani** [comment]
I "fixed" this in https://github.com/camunda-community-hub/console-customer-api-go/pull/9
